# Set env var for os specific configuration.
run-shell 'tmux setenv -g TMUX_OS $(uname -a | cut -d" " -f 1)'

# remap prefix from 'C-b' to 'C-f'
unbind C-b
set-option -g prefix C-f
bind-key C-f send-prefix

# Easier configuration reloads.
bind r source-file ~/.tmux.conf

# Enable mouse mode. Sometimes it is easier to use the mouse.
set -g mouse on

# Use system clipboard, but there are different clipboards in macos and linux.
set -g set-clipboard off
if-shell -b '[ "$TMUX_OS" = "Linux" ]' "\
  bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel \"xclip -se c -i\";\
  bind-key -n -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel \"xclip -se c -i\""
if-shell -b '[ "$TMUX_OS" = "Darwin" ]' "\
  bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel \"pbcopy\"; \
  bind-key -n -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel \"pbcopy\""

# split panes using | and -
bind | split-window -h
bind \\ split-window -h
bind - split-window -v
#unbind '"'
#unbind %

# Claude
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Theme
gray_Light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
gray_bg="#1f2127"
green_soft="#85c54d"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

#set -g status-position top
set -g status-left-length 100
set -g status-style "fg=${gray_Light},bg=${gray_bg}"
set -g status-left "[#[fg=${green_soft},bold] ▶︎ #S #[fg=${gray_Light},nobold]] | "
set -g status-right "#[fg=${green_soft},bold] %H:%M #[fg=${gray_Light}] | %a %d-%b-%y "

set -g window-status-current-format "#[fg=${cyan_soft},bold] 🞆 #[underscore]#I:#W"
set -g window-status-format " #I: #W"
set -g message-style "fg=${gray_Light},bg=default"
set -g mode-style "fg=${gray_dark},bg=${blue_muted}"

set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${gray_medium}"
